In [1]:
import pandas as pd

In [2]:
classes = pd.read_csv("full_list.csv")
classes.head()

,Class ID,Period,Course Title,Teacher,Term,Student
0,011010-01,1,Alg Readiness 8,"Aizaga, Richard N.",YR,"Aleman, Kevin G."
1,011010-01,1,Alg Readiness 8,"Aizaga, Richard N.",YR,"Arrechea, Noah J."
2,011010-01,1,Alg Readiness 8,"Aizaga, Richard N.",YR,"Carpenter, Henry J."
3,011010-01,1,Alg Readiness 8,"Aizaga, Richard N.",YR,"Carter, Bryce A."
4,011010-01,1,Alg Readiness 8,"Aizaga, Richard N.",YR,"Chavez Mejia, Pamela R."

In [16]:
students = pd.read_csv("missing.csv")
students.head()

                  Student  Student ID
0  Abdelgadir, Mohamed H.     1666381
1   Abdelgadir, Muhaid H.     1666379
2    Abdelkader, Farah A.     1633384
3     Abdelrahman, Ahd W.     1587223
4    Abdelrahman, Omer W.     1587094

In [17]:
merged = students.merge(classes, how='right', on=["Student"])
merged.head()

,Student,Student ID,Class ID,Period,Course Title,Teacher,Term
0,"Abdelgadir, Mohamed H.",1666381,235500-12,6,US History 7,"Chadowski, Melissa A.",YR
1,"Abdelgadir, Mohamed H.",1666381,993700-03,10,Team Desig 7th Gr,"Flood-Wright, Annece M.",YR
2,"Abdelgadir, Mohamed H.",1666381,712033-84,8,Health & PE 7,"Flynn, Bernadette",S1
3,"Abdelgadir, Mohamed H.",1666381,411536-02,2,Invest Env Sci HN,"Martinez, Bruce Edward D.",YR
4,"Abdelgadir, Mohamed H.",1666381,111036-05,7,English 7 HN,"Mohammad, Iman",YR

In [18]:
classes.count()

Class ID        8965
Period          8965
Course Title    8965
Teacher         8965
Term            8965
Student         8965
dtype: int64

In [19]:
merged.count()

Student         8965
Student ID      8965
Class ID        8965
Period          8965
Course Title    8965
Teacher         8965
Term            8965
dtype: int64

In [20]:
merged

,Student,Student ID,Class ID,Period,Course Title,Teacher,Term
0,"Abdelgadir, Mohamed H.",1666381,235500-12,6,US History 7,"Chadowski, Melissa A.",YR
1,"Abdelgadir, Mohamed H.",1666381,993700-03,10,Team Desig 7th Gr,"Flood-Wright, Annece M.",YR
2,"Abdelgadir, Mohamed H.",1666381,712033-84,8,Health & PE 7,"Flynn, Bernadette",S1
3,"Abdelgadir, Mohamed H.",1666381,411536-02,2,Invest Env Sci HN,"Martinez, Bruce Edward D.",YR
4,"Abdelgadir, Mohamed H.",1666381,111036-05,7,English 7 HN,"Mohammad, Iman",YR
5,"Abdelgadir, Mohamed H.",1666381,311136-04,1,Mathematics 7 HN,"Smith, Nakeisha L.",YR
6,"Abdelgadir, Mohamed H.",1666381,551300-08,5,Spanish 1 Part A,"Wadsworth, Mary D.",YR
7,"Abdelgadir, Mohamed H.",1666381,910532-04,3,Art Foundations,"Ziegler, Brian L.",S1
8,"Abdelgadir, Muhaid H.",1666379,993700-02,10,Team Desig 7th Gr,"Baldwin, Emily L.",YR
9,"Abdelgadir, Muhaid H.",1666379,235500-02,7,US History 7,"Foss, David A.",YR
10,"Abdelgadir, Muhaid H.",1666379,411500-18,6,Invest in Env Sci,"Reed, Lucian H.",YR
11,"Abdelgadir, Muhaid H.",1666379,111036-10,3,English 7 HN,"Thompson, Sarah M.",YR
12,"Abdelgadir, Muhaid H.",1666379,551300-03,8,Spanish 1 Part A,"Wadsworth, Mary D.",YR
13,"Abdelgadir, Muhaid H.",1666379,311100-06,2,Mathematics 7,"Yao, Yike",YR
14,"Abdelgadir, Muhaid H.",1666379,712033-69,1,Health & PE 7,"Yeo, Kimberly D.",S1
15,"Abdelgadir, Muhaid H.",1666379,910532-05,5,Art Foundations,"Ziegler, Brian L.",S1
16,"Abdelkader, Farah A.",1633384,111036-13,2,English 7 HN,"Fetterman, Amanda M.",YR
17,"Abdelkader, Farah A.",1633384,511300-03,3,French 1 Part A,"Houghton, Kathryn",YR
18,"Abdelkader, Farah A.",1633384,712033-01,6,Health & PE 7,"Jones, Stevaughn",S1
19,"Abdelkader, Farah A.",1633384,311136-02,1,Mathematics 7 HN,"Kim, Jenny Y.",YR
20,"Abdelkader, Farah A.",1633384,411536-16,5,Invest Env Sci HN,"Linton, Gretchen N.",YR
21,"Abdelkader, Farah A.",1633384,993700-01,10,Team Desig 7th Gr,"Pilotti, Leslie M.",YR
22,"Abdelkader, Farah A.",1633384,660932-03,8,Computer Solutions,"Reyes, Rolando",S1
23,"Abdelkader, Farah A.",1633384,235536-13,7,US History 7 HN,"Utterback, Kirstin L.",YR
24,"Abdelrahman, Ahd W.",1587223,235736-26,1,Civics 8 HN,"Allan, Mark R.",YR
25,"Abdelrahman, Ahd W.",1587223,551500-06,6,Spanish 1 Part B,"Anderson, Tammie S.",YR
26,"Abdelrahman, Ahd W.",1587223,993800-06,10,Team Desig 8th Gr,"Flood-Wright, Annece M.",YR
27,"Abdelrahman, Ahd W.",1587223,412536-05,5,Invest Mat/Ener HN,"Fortner, Jason",YR
28,"Abdelrahman, Ahd W.",1587223,720033-32,7,Health & PE 8,"Foster, Wade F.",S1
29,"Abdelrahman, Ahd W.",1587223,311200-05,2,Pre Algebra,"Mark, Dana T.",YR
...,...,...,...,...,...,...,...
8935,"Zenebe, Million",1596998,824432-05,7,FACS 2,"Hortz, Gena E.",S1
8936,"Zenebe, Million",1596998,720033-03,2,Health & PE 8,"McGarry, Lisa M.",S1
8937,"Zenebe, Million",1596998,112002-16,1,English 8 AA,"McNeil, Kenyetta",YR
8938,"Zenebe, Million",1596998,993800-05,10,Team Desig 8th Gr,"Pilotti, Leslie M.",YR
8939,"Zenebe, Million",1596998,313036-05,3,Algebra 1 HN,"Ryan, Andrew W.",YR
8940,"Zenebe, Million",1596998,412502-27,8,Invest Mat/Ener AA,"Saxena, Bhumika",YR
8941,"Zheng, Justin",1618854,993700-04,10,Team Desig 7th Gr,"Danosos, Maria L.",YR
8942,"Zheng, Justin",1618854,581300-01,6,Chinese 1 Part A,"Goetz, Ruth K.",YR
8943,"Zheng, Justin",1618854,923310-52,5,Intermediate Band,"Helm, Daniel P.",YR
8944,"Zheng, Justin",1618854,411500-15,3,Invest in Env Sci,"Holder, Jennifer",YR
8945,"Zheng, Justin",1618854,235500-15,7,US History 7,"Lomeo, Alexandra",YR
8946,"Zheng, Justin",1618854,111000-12,8,English 7,"Vacancy, English-1",YR
8947,"Zheng, Justin",1618854,311100-06,2,Mathematics 7,"Yao, Yike",YR
8948,"Zheng, Justin",1618854,712033-69,1,Health & PE 7,"Yeo, Kimberly D.",S1
8949,"Zhou, Vincent T.",1590425,314336-07,3,Geometry HN,"Behling, Lauren M.",YR
8950,"Zhou, Vincent T.",1590425,923911-01,7,Advanced Orchestra,"Garfield-Levine, Martin O.",YR
8951,"Zhou, Vincent T.",1590425,235702-03,5,Civics 8 AA,"Harvey, Renee A.",YR
8952,"Zhou, Vincent T.",1590425,720033-01,1,Health & PE 8,"McGarry, Lisa M.",S1
8953,"Zhou, Vincent T.",1590425,112002-01,8,English 8 AA,"McNeil, Kenyetta",YR
8954,"Zhou, Vincent T.",1590425,993800-05,10,Team Desig 8th Gr,"Pilotti, Leslie M.",YR
8955,"Zhou, Vincent T.",1590425,412502-01,6,Invest Mat/Ener AA,"Saxena, Bhumika",YR
8956,"Zhou, Vincent T.",1590425,551000-23,2,Spanish 1,"Soto, Carolina",YR
8957,"Zunic, Nicolas",1595717,313000-05,2,Algebra 1,"Aizaga, Richard N.",YR
8958,"Zunic, Nicolas",1595717,235736-10,5,Civics 8 HN,"Avila, Abigail E.",YR
8959,"Zunic, Nicolas",1595717,993800-07,10,Team Desig 8th Gr,"Baldwin, Emily L.",YR
8960,"Zunic, Nicolas",1595717,846332-09,6,Engr 2 Sim&Fab,"Gadson, Kimberly J.",S1
8961,"Zunic, Nicolas",1595717,720033-83,7,Health & PE 8,"Hay, Irvin L. Jr",S1
8962,"Zunic, Nicolas",1595717,112036-10,3,English 8 HN,"Hayman, Brittany M.",YR
8963,"Zunic, Nicolas",1595717,982816-03,1,AVID,"Miller, Jane L.",YR
8964,"Zunic, Nicolas",1595717,412536-11,8,Invest Mat/Ener HN,"Murtagh, Erin S.",YR

In [21]:
merged.to_csv("missing_list.csv")

In [13]:
merged['Class ID']

0       311200-02
1       412536-10
2       928510-01
3       235736-10
4       551500-06
5       720033-25
6       112000-08
7       993800-07
8       235500-13
9       846432-02
10      928510-01
11      311100-07
12      712033-01
13      111000-11
14      411500-20
15      993700-02
16      111002-02
17      235502-07
18      928510-01
19      411502-09
20      313036-03
21      712033-59
22      923810-05
23      993700-04
24      111000-06
25      311100-06
26      928510-01
27      910532-05
28      411500-03
29      235500-11
          ...
1761    313036-05
1762    235702-17
1763    923410-01
1764    412502-09
1765    824432-01
1766    993800-08
1767    311100-08
1768    111000-15
1769    411500-15
1770    923310-52
1771    581300-01
1772    235500-15
1773    712033-53
1774    993700-04
1775    720033-64
1776    551000-23
1777    112002-07
1778    235702-17
1779    412502-08
1780    923911-01
1781    314336-06
1782    993800-08
1783    982816-03
1784    112036-01
1785    313000-02
1786    720033-89
1787    846332-09
1788    235736-07
1789    412536-04
1790    993800-06
Name: Class ID, Length: 1791, dtype: object